version: "2"
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    networks: 
      - app-network
    volumes: 
      - .:/src
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
    ports:
      - "8000:8000"
    depends_on:
      - web

  web:
    build: .
    container_name: dg01
    networks:
      - app-network
    volumes: 
      - .:/src
      - ./static
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn finlance.wsgi -b 0.0.0.0:8000"
    expose:
      - "8000"

networks: 
  app-network:
    driver: bridge
