version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    network_mode: host
    ports:
      - "8000:8000"
    depends_on:
      - web

  web:
    build: .
    container_name: dg01
    network_mode: host
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn finlance.wsgi -b 0.0.0.0:8181"
    expose:
      - "8000"
