# Generated by Django 2.1.7 on 2020-02-28 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.EmployeeProfile')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Job')),
            ],
        ),
    ]
