# Generated by Django 3.0.2 on 2020-01-25 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='cv')),
                ('cover_letter', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='profile-pics/profile.png', upload_to='profile-pics')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
                ('id_number', models.CharField(max_length=8, unique=True)),
                ('status', models.CharField(choices=[('', ''), ('Hired', 'Not Looking for opportunity'), ('Available', 'Looking for new opportunity')], max_length=32)),
                ('is_suspended', models.BooleanField(default=False)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, default='Kenya', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=32)),
                ('proficiency', models.CharField(choices=[('', ''), ('Basic knowledge', 'Basic knowledge'), ('Good knowledge', 'Good knowledge'), ('Fluent', 'Fluent'), ('First language', 'First language')], max_length=63)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('', ''), ('English', 'English'), ('French', 'French'), ('Swahili', 'Swahili'), ('German', 'German'), ('Chinese', 'Chinese'), ('Arabic', 'Arabic'), ('Spanish', 'Spanish'), ('Hindustani', 'Hindusatani')], max_length=50)),
                ('proficiency', models.CharField(choices=[('', ''), ('Basic knowledge', 'Basic knowledge'), ('Good knowledge', 'Good knowledge'), ('Fluent', 'Fluent'), ('First language', 'First language')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=500)),
                ('company_homepage', models.URLField(blank=True)),
                ('job_type', models.CharField(choices=[('', 'Choose Employment Type'), ('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACTOR', 'Contractor'), ('TEMPORARY', 'Temporary'), ('INTERN', 'Intern'), ('VOLUNTEER', 'Volunteer'), ('PER_DIEM', 'Per Diem')], max_length=50)),
                ('company_size', models.CharField(blank=True, choices=[('', 'Company Size'), ('1-10 employees', '1-10 employees'), ('11-50 employees', '11-50 employees'), ('51-200 employees', '51-200 employees'), ('201-500 employees', '201-500 employees'), ('501-1,000 employees', '501-1,000 employees'), ('5,001-10,000 employees', '5,001-10,000 employees'), ('10,001 or more employees', '10,001 or more employees')], max_length=200)),
                ('industry', models.CharField(choices=[('Auditing', 'Auditing and Forensics'), ('Tax', 'Tax management and policy'), ('Book keeping', 'Financial records and reporting'), ('Financial Modelling', 'Financial Modelling'), ('Data Analysis', 'Data analysis and modeling')], max_length=500)),
                ('position', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current_job', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=500)),
                ('study_field', models.CharField(max_length=500)),
                ('certification', models.CharField(choices=[('PRIMARY_EDUCATION', 'Primary Education'), ('LOWER_SECONDARY_EDUCATION', 'Lower Secondary Education'), ('UPPER_SECONDARY_EDUCATION', 'Upper Secondary Education'), ('ASSOCIATES_OR_EQUIVALENT', 'Associates or Equivalent'), ('BACHELORS_OR_EQUIVALENT', 'Bachelors or Equivalent'), ('MASTERS_OR_EQUIVALENT', 'Masters or Equivalent'), ('DOCTORAL_OR_EQUIVALENT', 'Doctoral or Equivalent'), ('DEGREE_TYPE_UNSPECIFIED', 'Unspecified')], max_length=500)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
